name: localpkg_dart
description: A version of localpkg, but for Dart only.
version: 1.0.0
repository: https://github.com/Calebh101/localpkg-dart
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  yaml_edit: ^2.2.2
  http: ^1.5.0
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
